-- Davao City Food Types Database Update Script
-- Execute this in SQL Server Management Studio (SSMS)

-- First, clear existing food preferences to avoid foreign key constraints
DELETE FROM FoodPreferences;

-- Clear existing food types 
DELETE FROM FoodTypes;

-- Reset identity seed
DBCC CHECKIDENT('FoodTypes', RESEED, 0);

-- Insert comprehensive food types available in Davao City
INSERT INTO FoodTypes (Name, Description) VALUES

-- Filipino/Local Davao Specialties
('Durian', 'Davao''s famous king of fruits with strong aroma'),
('Durian Ice Cream', 'Creamy dessert made from Davao durian'),
('Durian Candy', 'Sweet candy made from local durian'),
('Pomelo', 'Large citrus fruit native to Davao'),
('Marang', 'Local tropical fruit similar to jackfruit'),
('Lanzones', 'Small sweet tropical fruit clusters'),
('Rambutan', 'Hairy red tropical fruit'),
('Mangosteen', 'Purple tropical fruit with white segments'),
('Davao Longganisa', 'Local sweet pork sausage'),
('Tuna Belly', 'Fresh grilled tuna belly, Davao specialty'),
('Grilled Tuna Jaw', 'Large grilled tuna jaw with tender meat'),
('Tuna Sashimi', 'Fresh raw tuna slices'),
('Tuna Kinilaw', 'Raw tuna cured in vinegar and spices'),
('Inihaw na Bangus', 'Grilled milkfish stuffed with tomatoes and onions'),
('Lechon Belly', 'Roasted pork belly with crispy skin'),
('Lechon Kawali', 'Deep-fried crispy pork belly'),
('Crispy Pata', 'Deep-fried pork leg with crispy skin'),
('Adobo', 'Filipino braised pork or chicken in soy sauce and vinegar'),
('Sinigang', 'Sour soup with tamarind and vegetables'),
('Kare-Kare', 'Oxtail stew in peanut sauce'),
('Bulalo', 'Beef shank soup with bone marrow'),
('Tinola', 'Chicken soup with ginger and green papaya'),
('Pancit Canton', 'Stir-fried wheat noodles with vegetables'),
('Pancit Bihon', 'Stir-fried rice noodles'),
('Lumpia Shanghai', 'Deep-fried spring rolls with meat filling'),
('Fresh Lumpia', 'Fresh spring rolls with vegetables'),
('Sisig', 'Sizzling chopped pork face and ears'),
('Bangus Sisig', 'Sizzling chopped milkfish'),
('Chicken Inasal', 'Grilled chicken marinated in annatto'),
('Pork BBQ', 'Filipino-style grilled pork skewers'),
('Chicken BBQ', 'Grilled chicken skewers'),
('Liempo', 'Grilled pork belly'),
('Chicharon', 'Deep-fried pork rinds'),
('Dinuguan', 'Pork blood stew'),
('Menudo', 'Pork and liver stew'),
('Caldereta', 'Goat or beef stew in tomato sauce'),
('Mechado', 'Beef stew with tomato sauce'),
('Afritada', 'Chicken or pork stew with vegetables'),
('Bicol Express', 'Spicy pork in coconut milk'),
('Laing', 'Taro leaves in coconut milk'),
('Pinakbet', 'Mixed vegetables with shrimp paste'),
('Ginataang Langka', 'Young jackfruit in coconut milk'),
('Halo-Halo', 'Mixed shaved ice dessert'),
('Leche Flan', 'Caramel custard dessert'),
('Buko Pie', 'Young coconut pie'),
('Bibingka', 'Rice cake with cheese and salted egg'),
('Puto', 'Steamed rice cake'),
('Kutsinta', 'Brown rice cake with coconut'),
('Taho', 'Soft tofu with syrup and tapioca pearls'),
('Balut', 'Duck embryo delicacy'),
('Kwek-Kwek', 'Deep-fried quail eggs in orange batter'),
('Fishball', 'Deep-fried fish balls'),
('Kikiam', 'Chinese-Filipino sausage rolls'),
('Isaw', 'Grilled chicken intestines'),
('Betamax', 'Grilled chicken blood cubes'),

-- Japanese Cuisine (Popular in Davao)
('Sushi', 'Japanese raw fish with seasoned rice'),
('Sashimi', 'Fresh raw fish slices'),
('Ramen', 'Japanese noodle soup'),
('Tempura', 'Battered and fried seafood or vegetables'),
('Teriyaki Chicken', 'Grilled chicken with sweet soy glaze'),
('Chicken Katsu', 'Breaded and fried chicken cutlet'),
('Pork Katsu', 'Breaded and fried pork cutlet'),
('California Maki', 'Sushi roll with crab and avocado'),
('Salmon Maki', 'Sushi roll with salmon'),
('Tuna Maki', 'Sushi roll with tuna'),
('Yakisoba', 'Stir-fried Japanese noodles'),
('Gyoza', 'Pan-fried pork dumplings'),
('Miso Soup', 'Soybean paste soup'),
('Chicken Teriyaki', 'Grilled chicken with teriyaki sauce'),
('Beef Teriyaki', 'Grilled beef with teriyaki sauce'),

-- Korean Cuisine (Growing popularity in Davao)
('Korean BBQ', 'Grilled marinated Korean meat'),
('Bulgogi', 'Marinated grilled beef'),
('Galbi', 'Marinated grilled short ribs'),
('Kimchi', 'Fermented spicy cabbage'),
('Bibimbap', 'Mixed rice bowl with vegetables'),
('Kimchi Fried Rice', 'Fried rice with kimchi'),
('Korean Fried Chicken', 'Crispy Korean-style fried chicken'),
('Japchae', 'Stir-fried sweet potato nooilles'),
('Tteokbokki', 'Spicy rice cakes'),
('Korean Ramyeon', 'Korean instant noodles'),

-- Chinese Cuisine
('Fried Rice', 'Stir-fried rice with vegetables and meat'),
('Yang Chow Fried Rice', 'Special fried rice with shrimp and Chinese sausage'),
('Sweet and Sour Pork', 'Battered pork in sweet and sour sauce'),
('Sweet and Sour Chicken', 'Battered chicken in sweet and sour sauce'),
('Chow Mein', 'Stir-fried noodles with vegetables'),
('Lo Mein', 'Soft noodles with sauce and vegetables'),
('Dumplings', 'Steamed or fried dough parcels'),
('Siomai', 'Steamed pork dumplings'),
('Xiao Long Bao', 'Soup dumplings'),
('Spring Rolls', 'Crispy vegetable rolls'),
('Wonton Soup', 'Soup with meat-filled dumplings'),
('Hot and Sour Soup', 'Spicy and tangy soup'),
('Mapo Tofu', 'Spicy tofu in Sichuan sauce'),
('Kung Pao Chicken', 'Spicy diced chicken with peanuts'),
('General Tso Chicken', 'Sweet and spicy fried chicken'),
('Orange Chicken', 'Battered chicken in orange sauce'),
('Beef and Broccoli', 'Stir-fried beef with broccoli'),
('Honey Walnut Shrimp', 'Fried shrimp with candied walnuts'),

-- Italian Cuisine
('Pizza Margherita', 'Classic pizza with tomato, mozzarella, and basil'),
('Pepperoni Pizza', 'Pizza with pepperoni slices'),
('Hawaiian Pizza', 'Pizza with ham and pineapple'),
('Meat Lovers Pizza', 'Pizza with multiple meat toppings'),
('Carbonara', 'Pasta with eggs, cheese, and bacon'),
('Bolognese', 'Pasta with meat sauce'),
('Alfredo', 'Pasta with cream and cheese sauce'),
('Aglio Olio', 'Pasta with garlic and olive oil'),
('Puttanesca', 'Pasta with tomatoes, olives, and anchovies'),
('Lasagna', 'Layered pasta with meat and cheese'),
('Ravioli', 'Stuffed pasta parcels'),
('Gnocchi', 'Potato dumplings with sauce'),
('Risotto', 'Creamy Italian rice dish'),
('Minestrone Soup', 'Italian vegetable soup'),
('Caesar Salad', 'Lettuce with Caesar dressing and croutons'),
('Caprese Salad', 'Tomato, mozzarella, and basil salad'),
('Tiramisu', 'Italian coffee-flavored dessert'),
('Gelato', 'Italian ice cream'),

-- American/Western Cuisine
('Burger', 'Grilled beef patty in a bun'),
('Cheeseburger', 'Burger with cheese'),
('Bacon Burger', 'Burger with bacon'),
('Chicken Burger', 'Grilled chicken breast in a bun'),
('Fish Burger', 'Fried fish fillet in a bun'),
('French Fries', 'Deep-fried potato strips'),
('Onion Rings', 'Battered and fried onion rings'),
('Chicken Wings', 'Fried or grilled chicken wings'),
('Buffalo Wings', 'Spicy chicken wings with buffalo sauce'),
('Fried Chicken', 'Crispy fried chicken pieces'),
('Grilled Chicken', 'Grilled chicken breast or thighs'),
('BBQ Ribs', 'Barbecued pork ribs'),
('Pulled Pork', 'Slow-cooked shredded pork'),
('Steak', 'Grilled beef steak'),
('T-Bone Steak', 'T-shaped beef steak'),
('Ribeye Steak', 'Marbled beef steak'),
('Fish and Chips', 'Battered fish with fried potatoes'),
('Mac and Cheese', 'Macaroni pasta with cheese sauce'),
('Meatloaf', 'Seasoned ground meat shaped into a loaf'),
('Meatballs', 'Seasoned ground meat balls'),
('Hot Dog', 'Grilled sausage in a bun'),
('Corn Dog', 'Battered and fried hot dog on a stick'),
('Pancakes', 'Fluffy breakfast cakes with syrup'),
('Waffles', 'Grid-patterned breakfast cakes'),
('Eggs Benedict', 'Poached eggs on English muffin with hollandaise'),
('Club Sandwich', 'Multi-layered sandwich with chicken and bacon'),
('BLT Sandwich', 'Bacon, lettuce, and tomato sandwich'),
('Grilled Cheese', 'Grilled sandwich with melted cheese'),

-- Mexican Cuisine
('Tacos', 'Folded tortillas with meat and vegetables'),
('Burritos', 'Large wrapped tortillas with fillings'),
('Quesadillas', 'Grilled tortillas with melted cheese'),
('Nachos', 'Tortilla chips with cheese and toppings'),
('Enchiladas', 'Rolled tortillas with sauce and cheese'),
('Fajitas', 'Grilled meat with peppers and onions'),
('Guacamole', 'Avocado dip with lime and spices'),
('Salsa', 'Tomato-based dip with chilies'),
('Churros', 'Fried dough pastry with cinnamon sugar'),
('Tres Leches', 'Three milk sponge cake'),

-- Thai Cuisine
('Pad Thai', 'Stir-fried noodles with tamarind sauce'),
('Tom Yum', 'Spicy and sour Thai soup'),
('Tom Kha', 'Coconut chicken soup'),
('Green Curry', 'Spicy green curry with coconut milk'),
('Red Curry', 'Spicy red curry with coconut milk'),
('Massaman Curry', 'Rich and mild Thai curry'),
('Pad Krapow', 'Stir-fried basil with meat'),
('Mango Sticky Rice', 'Sweet dessert with coconut sauce'),
('Thai Fried Rice', 'Fragrant fried rice with Thai flavors'),
('Som Tam', 'Spicy green papaya salad'),

-- Vietnamese Cuisine
('Pho', 'Vietnamese noodle soup with herbs'),
('Banh Mi', 'Vietnamese baguette sandwich'),
('Spring Rolls', 'Fresh rice paper rolls'),
('Vietnamese Fried Rice', 'Fragrant fried rice'),
('Bun Bo Hue', 'Spicy beef noodle soup'),

-- Indian Cuisine
('Chicken Curry', 'Spiced chicken in sauce'),
('Beef Curry', 'Spiced beef in sauce'),
('Vegetable Curry', 'Mixed vegetables in spiced sauce'),
('Chicken Tikka Masala', 'Chicken in creamy tomato sauce'),
('Butter Chicken', 'Mild chicken curry in butter sauce'),
('Biryani', 'Fragrant spiced rice with meat'),
('Tandoori Chicken', 'Clay oven-roasted spiced chicken'),
('Naan Bread', 'Indian flatbread'),
('Roti', 'Whole wheat flatbread'),
('Samosa', 'Fried pastry with spiced filling'),
('Dal', 'Lentil curry'),
('Palak Paneer', 'Spinach with Indian cottage cheese'),

-- Seafood (Davao specialty)
('Grilled Tuna', 'Fresh grilled tuna steak'),
('Grilled Salmon', 'Grilled salmon fillet'),
('Grilled Bangus', 'Grilled milkfish'),
('Grilled Tilapia', 'Grilled freshwater fish'),
('Fried Pompano', 'Deep-fried white fish'),
('Steamed Lapu-Lapu', 'Steamed grouper fish'),
('Grilled Squid', 'Grilled squid with soy sauce'),
('Grilled Prawns', 'Large grilled shrimp'),
('Shrimp Tempura', 'Battered and fried shrimp'),
('Crab in Coconut Milk', 'Crab cooked in coconut sauce'),
('Butter Garlic Shrimp', 'Shrimp in butter and garlic'),
('Salt and Pepper Fish', 'Crispy fish with salt and pepper'),

-- Healthy Options
('Quinoa Bowl', 'Nutritious grain bowl with vegetables'),
('Chicken Salad', 'Fresh salad with grilled chicken'),
('Tuna Salad', 'Fresh salad with tuna'),
('Greek Salad', 'Mediterranean salad with feta cheese'),
('Fruit Salad', 'Mixed fresh fruits'),
('Vegetable Salad', 'Mixed fresh vegetables'),
('Grilled Vegetables', 'Assorted grilled vegetables'),
('Steamed Vegetables', 'Healthy steamed mixed vegetables'),
('Vegetable Stir Fry', 'Quick-cooked mixed vegetables'),
('Tofu Stir Fry', 'Stir-fried tofu with vegetables'),
('Avocado Toast', 'Toasted bread with avocado spread'),
('Smoothie Bowl', 'Thick smoothie topped with fruits'),

-- Breakfast Items
('Tapsilog', 'Filipino beef tapa with rice and egg'),
('Longsilog', 'Filipino sausage with rice and egg'),
('Bangsilog', 'Milkfish with rice and egg'),
('Cornsilog', 'Corned beef with rice and egg'),
('Hotsilog', 'Hot dog with rice and egg'),
('Omelet', 'Beaten eggs cooked with fillings'),
('Scrambled Eggs', 'Softly cooked beaten eggs'),
('Fried Eggs', 'Eggs cooked sunny-side up or over easy'),
('Bacon and Eggs', 'Classic breakfast combination'),
('Ham and Eggs', 'Ham served with eggs'),
('French Toast', 'Bread soaked in egg and fried'),
('Cereals', 'Breakfast cereal with milk'),
('Oatmeal', 'Cooked oats with toppings'),

-- Snacks and Street Food
('Banana Cue', 'Deep-fried banana with brown sugar'),
('Camote Cue', 'Deep-fried sweet potato with brown sugar'),
('Turon', 'Deep-fried banana spring roll'),
('Biko', 'Sweet sticky rice cake'),
('Suman', 'Rice cake wrapped in banana leaves'),
('Mais Con Yelo', 'Corn with shaved ice and milk'),
('Dirty Ice Cream', 'Local ice cream in various flavors'),
('Popcorn', 'Popped corn kernels'),
('Potato Chips', 'Thin-sliced fried potatoes'),
('Crackers', 'Crispy baked snack crackers'),

-- Beverages (Food-related)
('Fresh Fruit Shake', 'Blended fresh fruits with ice'),
('Mango Shake', 'Blended mango with milk and ice'),
('Durian Shake', 'Blended durian with milk'),
('Avocado Shake', 'Creamy avocado smoothie'),
('Buko Juice', 'Fresh coconut water'),
('Calamansi Juice', 'Local lime juice'),
('Lemonade', 'Fresh lemon juice with water'),
('Iced Tea', 'Cold brewed tea'),
('Coffee', 'Hot brewed coffee'),
('Iced Coffee', 'Cold coffee drink'),
('Hot Chocolate', 'Hot cocoa drink'),

-- Desserts
('Ice Cream', 'Frozen dairy dessert'),
('Cake', 'Sweet baked dessert'),
('Chocolate Cake', 'Rich chocolate-flavored cake'),
('Cheesecake', 'Cream cheese-based cake'),
('Brownies', 'Dense chocolate squares'),
('Cookies', 'Sweet baked treats'),
('Donuts', 'Fried dough rings with glaze'),
('Pastries', 'Sweet baked goods'),
('Pie', 'Pastry with sweet or savory filling'),
('Pudding', 'Creamy dessert'),
('Jelly', 'Gelatin-based dessert'),
('Candy', 'Sweet confectionery'),
('Chocolate', 'Sweet cocoa-based treat');

-- Verify the insert
SELECT COUNT(*) as 'Total Food Types Inserted' FROM FoodTypes;

-- Display sample of inserted food types
SELECT TOP 20 FoodTypeId, Name, Description FROM FoodTypes ORDER BY Name;

PRINT 'Successfully inserted comprehensive Davao City food types!';
PRINT 'Total food types available for ranking and recommendations.';
